; Override for detect_mime(data, len) -> const char*
; Allocates a buffer, writes "application/gzip\0", returns it.
; Models the entire libmagic detection as returning gzip MIME type.
(declare @malloc ((size (Bitvector 64))) (Ptr 64))

(defun @detect_mime ((data (Ptr 64)) (len (Ptr 64))) (Ptr 64)
  (registers ($ptr (Ptr 64)))
  (start start:
    (let result (funcall @malloc (bv 64 32)))
    (set-register! $ptr result)
    ; "application/gzip\0"
    (pointer-write (Bitvector 8) le $ptr (bv 8 0x61))
    (let p1 (pointer-add $ptr (bv 64 1)))
    (pointer-write (Bitvector 8) le p1 (bv 8 0x70))
    (let p2 (pointer-add $ptr (bv 64 2)))
    (pointer-write (Bitvector 8) le p2 (bv 8 0x70))
    (let p3 (pointer-add $ptr (bv 64 3)))
    (pointer-write (Bitvector 8) le p3 (bv 8 0x6c))
    (let p4 (pointer-add $ptr (bv 64 4)))
    (pointer-write (Bitvector 8) le p4 (bv 8 0x69))
    (let p5 (pointer-add $ptr (bv 64 5)))
    (pointer-write (Bitvector 8) le p5 (bv 8 0x63))
    (let p6 (pointer-add $ptr (bv 64 6)))
    (pointer-write (Bitvector 8) le p6 (bv 8 0x61))
    (let p7 (pointer-add $ptr (bv 64 7)))
    (pointer-write (Bitvector 8) le p7 (bv 8 0x74))
    (let p8 (pointer-add $ptr (bv 64 8)))
    (pointer-write (Bitvector 8) le p8 (bv 8 0x69))
    (let p9 (pointer-add $ptr (bv 64 9)))
    (pointer-write (Bitvector 8) le p9 (bv 8 0x6f))
    (let p10 (pointer-add $ptr (bv 64 10)))
    (pointer-write (Bitvector 8) le p10 (bv 8 0x6e))
    (let p11 (pointer-add $ptr (bv 64 11)))
    (pointer-write (Bitvector 8) le p11 (bv 8 0x2f))
    (let p12 (pointer-add $ptr (bv 64 12)))
    (pointer-write (Bitvector 8) le p12 (bv 8 0x67))
    (let p13 (pointer-add $ptr (bv 64 13)))
    (pointer-write (Bitvector 8) le p13 (bv 8 0x7a))
    (let p14 (pointer-add $ptr (bv 64 14)))
    (pointer-write (Bitvector 8) le p14 (bv 8 0x69))
    (let p15 (pointer-add $ptr (bv 64 15)))
    (pointer-write (Bitvector 8) le p15 (bv 8 0x70))
    (let p16 (pointer-add $ptr (bv 64 16)))
    (pointer-write (Bitvector 8) le p16 (bv 8 0x00))
    (return result)))
